#pragma once


enum item_id_t
{
   ITEM_NO_ID = 0,
   ITEM_TORCH_ID,
   ITEM_RING_OF_LOFT_ID,
   ITEM_INFINITY_TORCH_ID,
   ITEM_TORCH_FUEL_ID,
   ITEM_TORCH_OF_TRUTH,

   // characters
   MAN_AT_THE_ENTRANCE_TO_THE_CAVE,
   CATALINA_IN_THE_VILLAGE,

   RAT = 100,
};
